---
title: "final_project"
author: "Olivia Wagner"
date: "11/16/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(arcos)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r load datasets}
opioid_death_data = janitor::clean_names(read_csv('./opioid_related_deaths.csv'))

opioid_er_data = janitor::clean_names(read_csv('./opioid_related_visits.csv'))

opioid_treatment_distance = janitor::clean_names(read_csv('./distance_to_treatment.csv'))
```

```{r pharma data}
prod_county = arcos::summarized_county_annual(state = "NY", key = "WaPo") %>% 
  janitor::clean_names()

county_pop = arcos::county_population(state = "NY", key = "WaPo") %>% 
  janitor::clean_names()
```


```{r data cleaning}

# clean opioid death data #

opioid_death_data = opioid_death_data %>% 
  filter(year >= 2010) 

# clean opioid er data #

opioid_er_data = opioid_er_data %>% 
  select(year, patient_county_name, rural_urban, payer, er_opioid, inpatient_total_opioid, er_inpatient_total_opioid, outpatient_opioid, overall_opioid) %>%
  rename(county = patient_county_name)

# clean opioid treatment data #
# data is only for the year 2017#

opioid_treatment_distance %>% 
  filter(state == 'New York') %>%
  select(state, county, value) %>%
  rename(distance = value) 


# Combine Data Sets #

opioid_total_data = left_join(opioid_er_data, opioid_death_data, by = c('county', 'year')) %>% 
  arrange(county, year) %>% 
  mutate(county = recode(county, "Kings (Brooklyn)" = "Kings",
         "New York (Manhattan)" = "New York"))

opioid_total_data %>% arrange(year, county) %>% print()

```

```{r number of pills}
# Number of Perscription Opioids by County #
prod_county %>% 
  group_by(buyer_county,year) %>% 
  summarize(numpills = sum(count)) %>% 
  arrange(desc(numpills))
```

```{r pills per capita}

# Pills bought by Pharmacies in Each county per Year #

pharma_df = left_join(prod_county, county_pop, by = c("buyer_county", "year")) %>% 
  select(county_name, year, count, population) %>% 
  rename(county = county_name,
         pills_bought = count) %>% 
  mutate(county = as.factor(county))
```

## fun with clustering

```{r}
int_slope_df =
  pharma_df %>% 
  nest(data = year:population) %>% 
  mutate(
    models = map(data, ~lm(pills_bought/population ~ year, data = .x)),
    result = map(models, broom::tidy)
  ) %>% 
  select(county, result) %>% 
  unnest(result) %>% 
  select(county, term, estimate) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>% 
  rename(int = "(Intercept)", slope = year)
  
```

```{r, results = "hide"}
int_slope_df %>% 
  ggplot(aes(x = int, y = slope)) + 
  geom_point()
```
```{r}
km_fit = 
  kmeans(
    x = int_slope_df %>% select(-county) %>% scale, 
    centers = 3)

int_slope_df =
  broom::augment(km_fit, int_slope_df)
```

```{r, results = "hide"}
int_slope_df %>% 
  ggplot(aes(x = int, y = slope, color = .cluster)) +
  geom_point()
```

```{r}
left_join(pharma_df, int_slope_df) %>% 
  ggplot(aes(x = year, y = pills_bought/population, group = county, color = .cluster)) + 
  geom_point() + 
  geom_path() 
```


```{r}
sum_df <- opioid_total_data %>% 
  group_by(county, year) %>% 
  summarize(er_opioid = sum(er_opioid),
            inpatient_total_opioid = sum(inpatient_total_opioid),
            er_inpatient_total_opioid = sum(er_inpatient_total_opioid),
            outpatient_opioid = sum(outpatient_opioid),
            overall_opioid = sum(overall_opioid),
            opioid_poisoning_deaths = sum(opioid_poisoning_deaths)
  )
```

```{r sales v outcomes}
death_sales_df <- inner_join(sum_df, pharma_df, by = c("county", "year")) %>% 
  ungroup() %>% 
  mutate(county = as.factor(county),
         year = as.factor(year),
         deaths_per_cap = opioid_poisoning_deaths/population)
```

## model building is fun

```{r}
fit1 <- lm(deaths_per_cap ~ pills_bought/population, data = death_sales_df)
fit2 <- lm(deaths_per_cap ~ . -er_inpatient_total_opioid -population, data = death_sales_df)
fit3 <- lm(deaths_per_cap ~ pills_bought, data = death_sales_df)
fit4 <- lm(deaths_per_cap ~ pills_bought * population, data = death_sales_df)
```

```{r, results = "hide"}
summary(fit1)
summary(fit2)
summary(fit3)
summary(fit4)
```

```{r}
model1 <- step(fit1)
```


```{r, results = "hide"}
death_sales_df %>% 
  ggplot(aes(x = pills_bought, y = opioid_poisoning_deaths, color = population)) +
  geom_point() +
  geom_smooth(se = FALSE)
```


```{r, results = "hide"}
anova(fit1)
```

