---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Motivation
**Provide an overview of the project goals and motivation.**
Given this, our goal in this project was to find out whether there is any meaningful information about demographics of people who were affected by opioid overdose. For instance, if certain age groups, gender, racial groups, or living condition accompanies with higher rates of opioid-related death in New York City. Also, we were interested in learning more about how these trends change over the years. We also look for any significant and meaningful information about the number of Emergency Room visits, the number of opioid-related death, and the number of pills prescribed to see if there is any meaningful and significant relationship between the different counties of New York City.


# Related work
Anything that inspired you, such as a paper, a web site, or something we discussed in class.

```{r include=FALSE}

library("htmltools")
library("vembedr")

embed_url("https://www.youtube.com/watch?v=ph0zvETOnmA")
```


# Initial questions

When investigating our datasets described below, we were primarily interested in urban vs rural communities as they related to opioid deaths. We were also interested in the county-level differences within New York, particularly because the state has such variety. Manhattan is very different from somewhere upstate, like Albany. We thought it would be interesting to consider the trends in pill prescription of different counties. Additionally, we wanted to look into opioid-related treatment visits in the counties in New York.

As the project evolved, we became curious about more individual-level data as well as the county level data described above. We thought that investigating demographics could provide insight into the opioid epidemic in New York. This led to questions about whether or not opioid deaths change over time with respect to race, age, or gender. Finally, we wanted to know if the type of insurance a person had related to the number of opioid-related facility visits. For example, were there more visits paid for by Medicare vs Medicaid?

_Our final research questions were as follows:_

* How do opioid deaths change over time in the following categories:

  * Race

  * Age

  * Gender

  * Rural/Urban

* How does the type of insurance a person has relate to the number of opioid-related facility visits?

* How do opioid related treatment visits and deaths differ by county?

* How do the number of pills prescribed differ by county over time?

# Data
Source, scraping method, cleaning, etc.


# Exploratory analysis
Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.


# Additional analysis

We conducted additional analysis on our data using model building techniques and clustering. The process

of model building included a stepwise regression on the parameters included in our data. VIF scores were

checked for multicollinearity in our variables. Finally, a simple model was proposed and then stepwise

regression was conducted to check for significance of the variables. A simple model was compared to the

complex model and determined to be preferable. 

Model building is a useful tool for prediction and inference. The types of models we used in this

analysis can be used for inference. Further analysis including cross validation or bootstrapping could

test the final model against future random samples to determine its predictive ability.

Clustering is a statistical tool that groups observations by location. For the purposes of this project

counties were grouped by the intercepts and slopes collected from linear models of various

opioid-related data adjusted for county population over time. These graphs indicate which counties might

have similar trends, for instance in order to apply available public health treatments in groups of

populations. Basically, there were some counties that started low and didn't change much, some that

started high and didn't change much, and some started in the middle and rose higher with time.

# Discussion: What were your findings? Are they what you expect? What insights into the data can you make?

Opioid related injuries included in our data sets were measured by emergency room visits, deaths, and

inpatient treatment. The number of opioids bought by pharmacies in each county was used as a proxy for

the number of pills sold in each county. There were demographic data available for deaths by opioid

overdose in New York City including the age group, race/ethnicity and gender of each subject.

A rural/urban variable was included in one dataset. We drew on this information to make our findings. 

Opioid overdose in New York City affect white people more than people of other races/ethnicities, and

more men as compared to women. Opioid overdose also tends to affect young adults (ages 25-34) more than

any other age group.

One finding that was not expected was that there was no apparent difference between rural and urban 

areas. This indicates that indicators associated with the urban/rural gradient, such as population 

density, may not have much effect on the prevalence of opioid related injuries. 

However, there was an association between the number of opioid related deaths in New York City

as compared with the rest of New York State when adjusting for the number of pills bought in each

county. So, this could be evidence that different interventions may be necessary to prevent opioid 

related injuries in counties outside the five boroughs. 

<<<<<<< HEAD
There were also statistical learning methods included. So, there was a search for trends in the data

that were not known. While there is an association between the pills bought per capita and the 

opioid deaths per 10,000 people, it may not be safe to assume that reducing opioid prescriptions would

decrease opioid injuries. Clustering counties by trends in the number of opioid related emergency room visits, 

opioid overdoses, and pills prescribed can reveal patterns that may be useful for deciding where and

how to distribute public health resources.
=======
Additionally, as discussed in the 
>>>>>>> 04195c703612d43882b57b7e17bd1461ef1735b0
